coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        # Lower patch coverage target to account for:
        # - LLVM coverage instrumentation quirks with multiline macros
        # - Error handling paths that are difficult to test
        target: 85%
